hannasbackend/hannasbackend/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from backendapp import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from backendapp.views import (
    CompanyViewSet,
    UserProfileViewSet,
    ReportTemplateViewSet,
    QuestionViewSet,
    ReportViewSet,
    AnswerViewSet,
    user_info,
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

router = DefaultRouter()
router.register(r"companies", CompanyViewSet)
router.register(r"userprofiles", UserProfileViewSet)
router.register(r"reporttemplates", ReportTemplateViewSet)
router.register(r"questions", QuestionViewSet)
router.register(r"reports", ReportViewSet, basename="report")
router.register(r"answers", AnswerViewSet)

urlpatterns = [
    path("api/", include(router.urls)),
    path("api/user/", user_info),
    path("admin/", admin.site.urls),
    path(
        "create-report-template/",
        views.create_report_template,
        name="create_report_template",
    ),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path(
        "update-report-template/<int:template_id>/",
        views.update_report_template,
        name="update_report_template",
    ),
    path(
        "get-template-questions/<int:template_id>/",
        views.get_template_questions,
        name="get_template_questions",
    ),
    path("accounts/profile/", views.profile_view, name="profile"),
    path("", views.home, name="home"),
    path("create-report/", views.create_report, name="create_report"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
]

hannasbackend/backendapp/models.py
from django.db import models
from django.conf import settings

from django.contrib.auth.models import Group, Permission
from django.db.models.signals import post_migrate
from django.dispatch import receiver


@receiver(post_migrate)
def create_user_roles(sender, **kwargs):
    superadmin, created = Group.objects.get_or_create(name="superadmin")
    admin, created = Group.objects.get_or_create(name="admin")
    user, created = Group.objects.get_or_create(name="user")

    if created:
        # Define permissions for each group
        # Superadmin has all permissions
        superadmin.permissions.set(Permission.objects.all())

        # Admin permissions
        admin_permissions = [
            "add_company",
            "change_company",
            "view_company",
            "delete_company",
            "add_report",
            "change_report",
            "view_report",
            "delete_report",
            # Add other permissions as needed
        ]
        admin.permissions.set(Permission.objects.filter(codename__in=admin_permissions))

        # User permissions
        user_permissions = [
            "add_report",
            "change_report",
            "view_report",
            # Add other permissions as needed
        ]
        user.permissions.set(Permission.objects.filter(codename__in=user_permissions))

        print("User roles created or updated successfully.")


class Company(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile"
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    is_company_admin = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class ReportTemplate(models.Model):
    name = models.CharField(max_length=100)
    accessible_by = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="accessible_templates"
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)

    # Add any other fields that might describe the template


class Question(models.Model):
    text = models.TextField()
    template = models.ForeignKey(
        ReportTemplate, related_name="questions", on_delete=models.CASCADE
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)

    # This sets up a many-to-one relationship to ReportTemplate


class Report(models.Model):
    report_title = models.CharField(max_length=100)
    submitted_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    template = models.ForeignKey(ReportTemplate, on_delete=models.SET_NULL, null=True)
    submitted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        related_name="submitted_reports",
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    # Include any other relevant fields


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    report = models.ForeignKey(Report, related_name="answers", on_delete=models.CASCADE)
    answer = models.CharField(max_length=255)  # or whatever field type you need
    explanation = models.TextField(blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)

hannasbackend/backendapp/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Report, ReportTemplate, Question


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = "__all__"


class ReportTemplateForm(forms.ModelForm):
    class Meta:
        model = ReportTemplate
        fields = ["name"]


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["text"]


QuestionFormset = inlineformset_factory(
    ReportTemplate, Question, form=QuestionForm, extra=0, can_delete=True
)

hannasbackend/backendapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.urls import path
from django.contrib.auth.models import User, Group
from .forms import ReportForm, ReportTemplateForm
from rest_framework import viewsets
from .models import Company, UserProfile, ReportTemplate, Question, Report, Answer
from .serializers import (
    CompanySerializer,
    UserProfileSerializer,
    ReportTemplateSerializer,
    QuestionSerializer,
    ReportSerializer,
    AnswerSerializer,
)
from .permissions import IsSuperAdmin, IsAdmin, IsUser, IsOwnerOrReadOnly
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated


@api_view(["GET"])
@permission_classes([IsAuthenticated])
def user_info(request):
    user = request.user
    return Response(
        {
            "username": user.username,
            "company": user.profile.company.name,  # Assuming a profile model with a company relationship
        }
    )


@api_view(["POST"])
def register_user(request):
    username = request.data.get("username")
    password = request.data.get("password")
    role = request.data.get("role")  # 'superadmin', 'admin', or 'user'

    if username is None or password is None or role is None:
        return Response(
            {"error": "Please provide username, password, and role"},
            status=status.HTTP_400_BAD_REQUEST,
        )

    if User.objects.filter(username=username).exists():
        return Response(
            {"error": "Username already exists"}, status=status.HTTP_400_BAD_REQUEST
        )

    user = User.objects.create_user(username=username, password=password)
    group = Group.objects.get(name=role)
    user.groups.add(group)

    return Response(
        {"message": "User created successfully"}, status=status.HTTP_201_CREATED
    )


@login_required
def home(request):
    return render(request, "home.html")


def user_is_company_admin(user):
    # Implement logic to check if the user is an admin of their company
    return (
        user.userprofile.is_admin
    )  # Example attribute, adjust according to your model


@login_required
def report_detail(request, report_id):
    report = Report.objects.get(id=report_id)
    return render(request, "report_detail.html", {"report": report})


def view_report(request, report_id):
    report = Report.objects.get(id=report_id)
    questions_with_answers = []
    print("omg")
    for question in report.template.questions.all():
        print(question)
        answers = question.answers.filter(report=report)
        questions_with_answers.append((question, answers))

    return render(
        request,
        "report_detail.html",
        {"report": report, "questions_with_answers": questions_with_answers},
    )


def profile_view(request):
    user_reports = Report.objects.filter(submitted_by=request.user)
    return render(request, "profile.html", {"reports": user_reports})


def report_list(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        reports = Report.objects.filter(company=user_profile.company)
    except UserProfile.DoesNotExist:
        reports = Report.objects.none()  # Or handle as appropriate

    return render(request, "reports/report_list.html", {"reports": reports})


def create_report_template(request):
    if request.method == "POST":
        form = ReportTemplateForm(request.POST)
        formset = QuestionFormset(request.POST)
        if form.is_valid() and formset.is_valid():
            report_template = form.save()
            formset.instance = report_template
            formset.save()
            # Redirect or handle as needed
    else:
        form = ReportTemplateForm()
        formset = QuestionFormset()

    return render(
        request, "create_report_template.html", {"form": form, "formset": formset}
    )


def update_report_template(request, template_id):
    template = get_object_or_404(ReportTemplate, id=template_id)
    if request.method == "POST":
        form = ReportTemplateForm(request.POST, instance=template)
        formset = QuestionFormset(request.POST, instance=template)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            # return redirect("some_view")  # Redirect to the desired view after update
    else:
        form = ReportTemplateForm(instance=template)
        formset = QuestionFormset(instance=template)

    return render(
        request,
        "update_report_template.html",
        {"form": form, "formset": formset, "template": template},
    )


def get_template_questions(request, template_id):
    template = get_object_or_404(ReportTemplate, id=template_id)
    questions = template.questions.all().values("id", "text")
    return JsonResponse(list(questions), safe=False)


def create_report(request):
    if request.method == "POST":
        form = ReportForm(request.POST)
        if form.is_valid():
            report = form.save()
            for key, value in request.POST.items():
                if key.startswith("answer_"):
                    question_id = key.split("_")[1]
                    question = Question.objects.get(id=question_id)
                    explanation_key = "explanation_" + question_id
                    explanation = request.POST.get(explanation_key, "")
                    Answer.objects.create(
                        report=report,
                        question=question,
                        answer=value,
                        explanation=explanation,
                    )
            return redirect(
                "some_success_url"
            )  # Redirect to a success page or the report detail view
    else:
        form = ReportForm()

    return render(request, "create_report.html", {"form": form})


class CompanyViewSet(viewsets.ModelViewSet):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer


class UserProfileViewSet(viewsets.ModelViewSet):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer


class ReportTemplateViewSet(viewsets.ModelViewSet):
    queryset = ReportTemplate.objects.all()
    serializer_class = ReportTemplateSerializer


class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer


class ReportViewSet(viewsets.ModelViewSet):
    queryset = Report.objects.all()  # Add this line
    serializer_class = ReportSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name="superadmin").exists():
            return Report.objects.all()
        elif user.groups.filter(name="admin").exists():
            return Report.objects.filter(company=user.profile.company)
        else:
            return Report.objects.filter(submitted_by=user)

    def perform_create(self, serializer):
        serializer.save(
            submitted_by=self.request.user, company=self.request.user.profile.company
        )


class AnswerViewSet(viewsets.ModelViewSet):
    queryset = Answer.objects.all()
    serializer_class = AnswerSerializer

hannasbackend/backendapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'backendapp/css/style.css' %}">
    <!-- Add any CSS or JS links here -->
</head>
<body>
    <div class="navbar">
        <div class="logo">MySite</div>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <!-- More navigation items here -->
            {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
            
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
    

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

hannasbackend/backendapp/templates/create_report.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="questions-container">
        <!-- Dynamic questions will be appended here -->
    </div>
    <button type="submit">Submit</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_template').change(function () {
            var templateId = $(this).val();
            $.ajax({
                url: '/get-template-questions/' + templateId,
                success: function (questions) {
                    // Clear existing questions
                    $('#questions-container').empty();

                    // Add new questions
                    questions.forEach(function (question) {
                        $('#questions-container').append(
                            '<div>' + question.text + ': ' +
                            '<input type="radio" name="answer_' + question.id + '" value="yes"> Yes ' +
                            '<input type="radio" name="answer_' + question.id + '" value="no"> No ' +
                            '<input type="radio" name="answer_' + question.id + '" value="na"> Not Applicable ' +
                            '<input type="radio" name="answer_' + question.id + '" value="nr"> Not Answered ' +
                            '<input type="text" name="explanation_' + question.id + '" placeholder="Explanation">' +
                            '</div>'
                        );
                    });
                }
            });
        });
    });
</script>

hannasbackend/backendapp/templates/create_report_template.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="formset">
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="formset-form">
                {{ form.as_p }}
                <button type="button" class="remove-form">Remove</button>
            </div>
        {% endfor %}
    </div>
    <button type="button" id="add-form">Add Question</button>
    <button type="submit">Submit</button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#add-form').click(function() {
        var formCount = parseInt($('#id_questions-TOTAL_FORMS').val());
        var newForm = $('#empty-form').html().replace(/__prefix__/g, formCount);
        $('#formset').append(newForm);
        $('#id_questions-TOTAL_FORMS').val(formCount + 1);
    });

        $(document).on('click', '.remove-form', function () {
            $(this).parent('.formset-form').remove();
        });
    });
</script>

<!-- Empty form template for cloning -->
<div id="empty-form" style="display:none;">
    <div class="formset-form">
        {{ formset.empty_form.as_p }}
        <button type="button" class="remove-form">Remove</button>
    </div>
</div>

hannasbackend/backendapp/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home - My Site{% endblock %}

{% block content %}
    <h1>Welcome to the Home Page</h1>
    <!-- Page-specific content goes here -->
{% endblock %}

hannasbackend/backendapp/templates/login.html
<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <label for="id_username">Username:</label>
    <input type="text" name="username" id="id_username" required><br>

    <label for="id_password">Password:</label>
    <input type="password" name="password" id="id_password" required><br>

    <button type="submit">Login</button>
</form>

hannasbackend/backendapp/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<h2>Your Reports</h2>
{% if reports %}
    <ul>
        {% for report in reports %}
            <li>
                <strong>{{ report.report_title }}</strong> (submitted on {{ report.submitted_on }})<br>
                Last updated: {{ report.last_updated }}<br>
                <!-- Display other fields as needed -->
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>You have not submitted any reports.</p>
{% endif %}
{% endblock %}

hannasbackend/backendapp/templates/report_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Report Details</title>
    <style>
        .report-container { font-family: monospace; }
        .report-field { margin-left: 20px; }
    </style>
</head>
<body>
    <div class="report-container">
        <p>{</p>

        <div class="report-field">"id": "{{ report.id }}",</div>
        <div class="report-field">"report_title": "{{ report.report_title }}",</div>
        <div class="report-field">"submitted_on": "{{ report.submitted_on }}",</div>
        <div class="report-field">"last_updated": "{{ report.last_updated }}",</div>
        <div class="report-field">"template": {</div>
        <div class="report-field">"id": "{{ report.template.id }}",</div>
        <div class="report-field">"name": "{{ report.template.name }}",</div>
        <div class="report-field">"questions": [</div>
        
        {% for question in report.template.questions.all %}
            <div class="report-field">{
                <div class="report-field">"id": "{{ question.id }}",</div>
                <div class="report-field">"text": "{{ question.text }}",</div>
                <div class="report-field">"answers": [</div>
                {% for answer in report.answers.all %}
                    {% if answer.question.id == question.id %}
                        <div class="report-field">{ "answer": "{{ answer.answer }}", "explanation": "{{ answer.explanation }}" }</div>
                    {% endif %}
                {% endfor %}
                <div class="report-field">]</div>
            <div class="report-field">},</div>
        {% endfor %}

        <div class="report-field">]</div>
        <div class="report-field">}</div>
        
        <p>}</p>
    </div>
</body>
</html>

hannasbackend/backendapp/templates/update_report_template.html
{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="formset">
    {{ formset.management_form }}
    {% for form in formset %}
    <div class="formset-form">
        {{ form.as_p }}
        {{ form.DELETE }}  <!-- Important: Include the DELETE field -->
        <button type="button" class="remove-form">Remove</button>
    </div>
    {% endfor %}
</div>
    <button type="button" id="add-form">Add Question</button>
    <button type="submit">Update</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function () {
          $('#add-form').click(function() {
          var formCount = parseInt($('#id_questions-TOTAL_FORMS').val());
          var newForm = $('#empty-form').html().replace(/__prefix__/g, formCount);
          $('#formset').append(newForm);
          $('#id_questions-TOTAL_FORMS').val(formCount + 1);
      });
  
    $(document).on('click', '.remove-form', function () {
        var formCount = $('#id_questions-TOTAL_FORMS').val();
        if (formCount > 1) {
            $(this).closest('.formset-form').find('input[type=checkbox]').prop('checked', true);
            $(this).closest('.formset-form').hide();
            formCount--;
            $('#id_questions-TOTAL_FORMS').val(formCount);
        }
    });

      });
  </script>
<div id="empty-form" style="display:none;">
    <div class="formset-form">
        {{ formset.empty_form.as_p }}
        <button type="button" class="remove-form">Remove</button>
    </div>
</div>
{% endblock %}